temperature:
  player: 30
  biomes:
    default: 20
    BADLANDS: 38
    BADLANDS_PLATEAU: 40
    BAMBOO_JUNGLE: 30
    BAMBOO_JUNGLE_HILLS: 25
    BEACH: 20
    BIRCH_FOREST: 10
    BIRCH_FOREST_HILLS: 8
    COLD_OCEAN: -2
    DARK_FOREST: 8
    DARK_FOREST_HILLS: 6
    DEEP_COLD_OCEAN: -8
    DEEP_FROZEN_OCEAN: -16
    DEEP_LUKEWARM_OCEAN: 8
    DEEP_OCEAN: 0
    DEEP_WARM_OCEAN: 16
    DESERT: 40
    DESERT_HILLS: 38
    DESSERT_LAKES: 36
    END_BARRENS: 0
    END_HIGHLANDS: 20
    END_MIDLANDS: 10
    ERODED_BADLANDS: 38
    FLOWER_FOREST: 12
    FOREST: 10
    FROZEN_OCEAN: -12
    FROZEN_RIVER: -10
    GIANT_SPRUCE_TAIGA: -10
    GIANT_SPRUCE_TAIGA_HILLS: -12
    GIANT_TREE_TAIGA: -10
    GIANT_TREE_TAIGA_HILLS: -12
    GRAVELLY_MOUNTAINS: 4
    ICE_SPIKES: -10
    JUNGLE: 30
    JUNGLE_EDGE: 25
    JUNGLE_HILLS: 28
    LUKEWARM_OCEAN: 10
    MODIFIED_BADLANDS_PLATEAU: 40
    MODIFIED_GRAVELLY_MOUNTAINS: 4
    MODIFIED_JUNGLE: 30
    MODIFIED_JUNGLE_EDGE: 25
    MODIFIED_WOODED_BADLANDS_PLATEU: 45
    MOUNTAIN_EDGE: 6
    MOUNTAINS: 4
    MUSHROOM_FIELD_SHORE: 10
    MUSHROOM_FIELDS: 10
    NETHER: 75
    OCEAN: 2
    PLAINS: 5
    RIVER: 4
    SAVANNA: 28
    SAVANNA_PLATEAU: 30
    SHATTERED_SAVANNA: 28
    SHATTERED_SAVANNA_PLATEAU: 30
    SMALL_END_ISLANDS: 10
    SNOWY_BEACH: 10
    SNOWY_MOUNTAINS: 2
    SNOWY_TAIGA: -8
    SNOWY_TAIGA_HILLS: -10
    SNOWY_TAIGA_MOUNTAINS: -12
    SNOWY_TUNDRA: -14
    STONE_SHORE: -8
    SUNFLOWER_PLAINS: 8
    SWAMP: 5
    SWAMP_HILLS: 3
    TAIGA: -6
    TAIGA_HILLS: -8
    TAIGA_MOUNTAINS: -10
    TALL_BIRCH_FOREST: 12
    TALL_BIRCH_HILLS: 10
    THE_END: 10
    THE_VOID: 0
    WARM_OCEAN: 18
    WOODED_BADLANDS_PLATEAU: 42
    WOODED_HILLS: 8
    WODED_MOUNTAINS: 6